apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: vazavhorodny.xyz-tls
spec:
  secretName: vazavhorodny.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vazavhorodny.xyz
  dnsNames:
    - vazavhorodny.xyz
    - www.vazavhorodny.xyz
